### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by diega** [TapuCosmo/liboqs-node#1]
Hello,
I'm trying to load the `liboqs-node` module but I'm getting the following error:

```
Error: Could not locate the bindings file. Tried:
 → /node_modules/liboqs-node/build/oqs_node.node
 → /node_modules/liboqs-node/build/Debug/oqs_node.node
 → /node_modules/liboqs-node/build/Release/oqs_node.node
 → /node_modules/liboqs-node/out/Debug/oqs_node.node
 → /node_modules/liboqs-node/Debug/oqs_node.node
 → /node_modules/liboqs-node/out/Release/oqs_node.node
 → /node_modules/liboqs-node/Release/oqs_node.node
 → /node_modules/liboqs-node/build/default/oqs_node.node
 → /node_modules/liboqs-node/compiled/14.15.4/linux/x64/oqs_node.node
 → /node_modules/liboqs-node/addon-build/release/install-root/oqs_node.node
 → /node_modules/liboqs-node/addon-build/debug/install-root/oqs_node.node
 → /node_modules/liboqs-node/addon-build/default/install-root/oqs_node.node
 → /node_modules/liboqs-node/lib/binding/node-v83-linux-x64/oqs_node.node
    at bindings (/node_modules/liboqs-node/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/node_modules/liboqs-node/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3) {
  tries: [
    '/node_modules/liboqs-node/build/oqs_node.node',
    '/node_modules/liboqs-node/build/Debug/oqs_node.node',
    '/node_modules/liboqs-node/build/Release/oqs_node.node',
    '/node_modules/liboqs-node/out/Debug/oqs_node.node',
    '/node_modules/liboqs-node/Debug/oqs_node.node',
    '/node_modules/liboqs-node/out/Release/oqs_node.node',
    '/node_modules/liboqs-node/Release/oqs_node.node',
    '/node_modules/liboqs-node/build/default/oqs_node.node',
    '/node_modules/liboqs-node/compiled/14.15.4/linux/x64/oqs_node.node',
    '/node_modules/liboqs-node/addon-build/release/install-root/oqs_node.node',
    '/node_modules/liboqs-node/addon-build/debug/install-root/oqs_node.node',
    '/node_modules/liboqs-node/addon-build/default/install-root/oqs_node.node',
    '/node_modules/liboqs-node/lib/binding/node-v83-linux-x64/oqs_node.node'
  ]
}
```

This is the smallest Docker image I was able to create to reproduce the issue
```docker
FROM node:lts-buster-slim

RUN apt-get update && apt-get install --no-install-recommends -yV \
    cmake \
    ninja-build \
    gcc \
    libc6-dev \
    libssl-dev

RUN npm install liboqs-node
```
This can be built by doing
`$ docker build . -t liboqs_node_env`
and you can preload the module by running
`$ docker run liboqs_node_env --require liboqs-node`
then you should see the quoted error message

**Comment by TapuCosmo** [comment]
I've created Linux binaries and fixed the build process. The new v0.1.0 release should install properly.
